# Generated by Django 3.2 on 2025-03-11 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('first_name', models.CharField(max_length=30)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Month',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('Jan', 'Jan'), ('Feb', 'Feb'), ('Mar', 'Mar'), ('Apr', 'Apr'), ('May', 'May'), ('Jun', 'Jun'), ('Jul', 'Jul'), ('Aug', 'Aug'), ('Sep', 'Sep'), ('Oct', 'Oct'), ('Nov', 'Nov'), ('Dec', 'Dec')], max_length=3, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Package',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Place', models.CharField(max_length=60)),
                ('Country', models.CharField(max_length=60)),
                ('State', models.CharField(max_length=60)),
                ('Price', models.FloatField()),
                ('Days', models.PositiveSmallIntegerField()),
                ('Night', models.PositiveSmallIntegerField()),
                ('Description', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
                ('Image', models.ImageField(upload_to='image')),
                ('Image2', models.ImageField(upload_to='image')),
                ('Image3', models.ImageField(upload_to='image')),
                ('Image4', models.ImageField(upload_to='image')),
                ('StartDate', models.JSONField(default=list)),
                ('EndDate', models.JSONField(default=list)),
                ('Total_Person', models.PositiveIntegerField(default=1)),
                ('Month', models.ManyToManyField(to='app.Month')),
            ],
        ),
    ]
