# Generated by Django 3.2 on 2025-03-12 00:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_book_package'),
    ]

    operations = [
        migrations.DeleteModel(
            name='book_package',
        ),
    ]
