# Generated by Django 3.2 on 2025-03-12 00:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_delete_book_package'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='package',
            name='Days',
        ),
        migrations.RemoveField(
            model_name='package',
            name='Description',
        ),
        migrations.RemoveField(
            model_name='package',
            name='EndDate',
        ),
        migrations.RemoveField(
            model_name='package',
            name='Image',
        ),
        migrations.RemoveField(
            model_name='package',
            name='Image2',
        ),
        migrations.RemoveField(
            model_name='package',
            name='Image3',
        ),
        migrations.RemoveField(
            model_name='package',
            name='Image4',
        ),
        migrations.RemoveField(
            model_name='package',
            name='Month',
        ),
        migrations.RemoveField(
            model_name='package',
            name='Night',
        ),
        migrations.RemoveField(
            model_name='package',
            name='Price',
        ),
        migrations.RemoveField(
            model_name='package',
            name='StartDate',
        ),
        migrations.RemoveField(
            model_name='package',
            name='State',
        ),
        migrations.RemoveField(
            model_name='package',
            name='Total_Person',
        ),
        migrations.RemoveField(
            model_name='package',
            name='is_active',
        ),
    ]
