# Generated by Django 3.2 on 2025-03-12 00:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20250312_0555'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Package',
            new_name='packages',
        ),
    ]
