# Generated by Django 3.2 on 2025-03-12 00:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_month_package'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='package',
            name='Month',
        ),
        migrations.DeleteModel(
            name='Month',
        ),
        migrations.DeleteModel(
            name='Package',
        ),
    ]
