# Generated by Django 3.2 on 2025-03-12 00:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_rename_package_packages'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Packages',
        ),
    ]
