# Generated by Django 3.2 on 2025-03-12 00:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_delete_packages'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Month',
        ),
    ]
