# Generated by Django 3.2 on 2025-03-13 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_auto_20250312_0627'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='is_treding',
            field=models.BooleanField(default=False),
        ),
    ]
