# Generated by Django 3.2 on 2025-03-13 01:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_package_is_treding'),
    ]

    operations = [
        migrations.RenameField(
            model_name='package',
            old_name='is_treding',
            new_name='is_trending',
        ),
    ]
