# Generated by Django 3.2 on 2025-03-17 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_rename_is_treding_package_is_trending'),
    ]

    operations = [
        migrations.RenameField(
            model_name='package',
            old_name='Country',
            new_name='country',
        ),
        migrations.RenameField(
            model_name='package',
            old_name='Days',
            new_name='days',
        ),
        migrations.RenameField(
            model_name='package',
            old_name='EndDate',
            new_name='days_plan',
        ),
        migrations.RenameField(
            model_name='package',
            old_name='Description',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='package',
            old_name='StartDate',
            new_name='end_dates',
        ),
        migrations.RenameField(
            model_name='package',
            old_name='Month',
            new_name='months',
        ),
        migrations.RenameField(
            model_name='package',
            old_name='Night',
            new_name='nights',
        ),
        migrations.RenameField(
            model_name='package',
            old_name='Place',
            new_name='place',
        ),
        migrations.RenameField(
            model_name='package',
            old_name='Price',
            new_name='price',
        ),
        migrations.RenameField(
            model_name='package',
            old_name='State',
            new_name='state',
        ),
        migrations.RenameField(
            model_name='package',
            old_name='Total_Person',
            new_name='total_person',
        ),
        migrations.RemoveField(
            model_name='package',
            name='Image',
        ),
        migrations.RemoveField(
            model_name='package',
            name='Image2',
        ),
        migrations.RemoveField(
            model_name='package',
            name='Image3',
        ),
        migrations.RemoveField(
            model_name='package',
            name='Image4',
        ),
        migrations.AddField(
            model_name='package',
            name='image1',
            field=models.ImageField(default=1, upload_to='images/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='package',
            name='image2',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='package',
            name='image3',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='package',
            name='image4',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='package',
            name='start_dates',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='month',
            name='name',
            field=models.CharField(choices=[('Jan', 'January'), ('Feb', 'February'), ('Mar', 'March'), ('Apr', 'April'), ('May', 'May'), ('Jun', 'June'), ('Jul', 'July'), ('Aug', 'August'), ('Sep', 'September'), ('Oct', 'October'), ('Nov', 'November'), ('Dec', 'December')], max_length=3, unique=True),
        ),
    ]
