# Generated by Django 3.2 on 2025-03-17 17:54

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0021_auto_20250317_2258'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='package',
            name='months',
        ),
        migrations.AddField(
            model_name='package',
            name='months',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('Jan', 'January'), ('Feb', 'February'), ('Mar', 'March'), ('Apr', 'April'), ('May', 'May'), ('Jun', 'June'), ('Jul', 'July'), ('Aug', 'August'), ('Sep', 'September'), ('Oct', 'October'), ('Nov', 'November'), ('Dec', 'December')], default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Month',
        ),
    ]
